### ISSUE TITLE
black background when converting from png to jpeg

### ISSUE THREAD

**Issue by HamzaMihfad** [alefduarte/image-resize-compress#11]
Thank you for this awesome backage, is there any way that allow as to choose the background color when converting from jpeg to png, in my case i want a white background

**Comment by alefduarte** [comment]
Fixed by #29 
I've added a new option `backgroundColor`.
``` js
fromBlob(imgBlob, 80, 300, 200, 'jpeg', '#FFFFFF');
```

**Comment by KerryRitter** [comment]
Just a note for anyone else - I had the same issue with converting to `webp`. I upgraded to the latest and set the backgroundColor as 'transparent' and it was successful. Thanks for a great tool @alefduarte!
